### ISSUE TITLE
Not compatible with react-native@"0.64.2"

### ISSUE THREAD

**Issue by edward-sentongo** [bruchim/react-native-perf-logger#4]
As a project requirement, I have to use "**package.json**" to install this package.

Our project uses the lates react-native 0.64.2

Running '**npm install**' results in an error:

npm ERR! node_modules/react
npm ERR!   peer react@"^16.8.1" from react-native-perf-logger@2.0.1
npm ERR!   node_modules/react-native-perf-logger
npm ERR!     react-native-perf-logger@"2.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.1" from react-native@0.64.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.64.2" from the root project
npm ERR!   **peer react-native@">=0.59.0-rc.0 <1.0.x" from react-native-perf-logger@2.0.1**
npm ERR!   node_modules/react-native-perf-logger
npm ERR!     react-native-perf-logger@"2.0.1" from the root project

Your package is depended upon by several other node modules. We simply can't delete it.

Thanks in advance

**Comment by markl-vesper** [comment]
Hi Edward

I did not seem to have any issues on 64.2 with yarn install after adding the package. Yarn worked fine

`react-native-perf-logger": "^2.0.1",

what a nightmare trying to get it to run the app however. 

It first starting complaining about the include line in PerfLogger.h. After changing the include line

`#import <React/RCTBridgeModule.h> => #import "RCTBridgeModule.h"`

it now produces further compile errors

```
/Users/developer/cortexMonitoring/node_modules/react-native/ReactCommon/cxxreact/ModuleRegistry.cpp:11:10: fatal error: 'reactperflogger/BridgeNativeModulePerfLogger.h' file not found
#include <reactperflogger/BridgeNativeModulePerfLogger.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

the question I ask myself is why on earth would we ever need to mess around with such low level stuff??

**Comment by edward-sentongo** [comment]
> Hi Edward
> 
> I did not seem to have any issues on 64.2 with yarn install after adding the package. Yarn worked fine
> 
> `react-native-perf-logger": "^2.0.1",
> 
> what a nightmare trying to get it to run the app however.
> 
> It first starting complaining about the include line in PerfLogger.h. After changing the include line
> 
> `#import <React/RCTBridgeModule.h> => #import "RCTBridgeModule.h"`
> 
> it now produces further compile errors
> 
> ```
> /Users/developer/cortexMonitoring/node_modules/react-native/ReactCommon/cxxreact/ModuleRegistry.cpp:11:10: fatal error: 'reactperflogger/BridgeNativeModulePerfLogger.h' file not found
> #include <reactperflogger/BridgeNativeModulePerfLogger.h>
>          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> ```
> 
> the question I ask myself is why on earth would we ever need to mess around with such low level stuff??

**Comment by edward-sentongo** [comment]
@markl-vesper thank you for your feedback.
However, as a requirement for our build process and pipelines, we can only use '`npm install`'

**Comment by markl-vesper** [comment]
is this a joke? no yarn?

**Comment by edward-sentongo** [comment]
@markl-vesper no joke. there are teams which still use npm.
I closed the issue/ticket because the vendor of the module which depended on perf-logger fixed their module. So all is working great on our side.
